-- MySQL Script generated by MySQL Workbench
-- Mon Oct 29 12:09:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TIPO_DE_PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TIPO_DE_PAGO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_DE_PAGO` (
  `numero` INT NOT NULL,
  `tipoDeTarjeta` VARCHAR(30) NOT NULL,
  `fechaDeVencimiento` DATE NOT NULL,
  `codigoDeSeguridad` INT NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VENTA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VENTA` (
  `id` INT NOT NULL,
  `fechaYHora` DATE NOT NULL,
  `numeroDeTarjeta` BIGINT(20) NOT NULL,
  `importe` DOUBLE NOT NULL,
  `TIPO_DE_PAGO_numero` INT NOT NULL,
  `esPorPortal` BIT(1) NOT NULL,
  PRIMARY KEY (`id`, `TIPO_DE_PAGO_numero`),
  INDEX `fk_VENTA_TIPO_DE_PAGO_idx` (`TIPO_DE_PAGO_numero` ASC),
  CONSTRAINT `fk_VENTA_TIPO_DE_PAGO`
    FOREIGN KEY (`TIPO_DE_PAGO_numero`)
    REFERENCES `mydb`.`TIPO_DE_PAGO` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entrada` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entrada` (
  `columna` VARCHAR(10) NOT NULL,
  `fila` VARCHAR(10) NOT NULL,
  `id` INT NOT NULL,
  `ocupado` BIT(1) NOT NULL,
  `VENTA_id` INT NOT NULL,
  `VENTA_TIPO_DE_PAGO_numero` INT NOT NULL,
  PRIMARY KEY (`columna`, `fila`, `VENTA_id`, `VENTA_TIPO_DE_PAGO_numero`),
  INDEX `fk_entrada_VENTA1_idx` (`VENTA_id` ASC, `VENTA_TIPO_DE_PAGO_numero` ASC),
  CONSTRAINT `fk_entrada_VENTA1`
    FOREIGN KEY (`VENTA_id` , `VENTA_TIPO_DE_PAGO_numero`)
    REFERENCES `mydb`.`VENTA` (`id` , `TIPO_DE_PAGO_numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
